//! # Skin Bridge
//!
//! Inter-crate pipeline: Integumentary → Immunity.
//!
//! Converts integumentary `SkinCondition` and sensor readings into
//! immunity threat signals that trigger the immune scanning pipeline.
//!
//! ```text
//! Integumentary::SkinCondition → ThreatLevel (skin-detected threats)
//! Integumentary::SensorStatus → ThreatType (PAMP for external, DAMP for internal)
//! Integumentary::Shield → immune readiness assessment
//! ```
//!
//! **Biological mapping**: The skin (integumentary system) is the body's
//! first line of defense. When the skin detects a breach (pain sensor alert,
//! high temperature, abnormal pressure), it signals the immune system to
//! mount a response. Commensal bacteria on healthy skin actually help train
//! the immune system — similarly, normal sensor readings calibrate immunity.

use nexcore_integumentary::{SensorStatus, Shield, SkinCondition};

use crate::{ThreatLevel, ThreatType};

/// Skin-derived immune alert containing threat classification.
///
/// **Biological mapping**: Keratinocyte alarm signal — when skin cells
/// detect damage, they release cytokines that activate local immune cells
/// (Langerhans cells) embedded in the epidermis.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkinAlert {
    /// How severe the skin-detected threat is.
    pub threat_level: ThreatLevel,
    /// Whether the threat is external (PAMP) or internal (DAMP).
    pub threat_type: ThreatType,
    /// Description of what triggered the alert.
    pub description: String,
}

/// Convert a `SkinCondition` into a list of immune alerts.
///
/// Each abnormal sensor reading produces an alert. Normal conditions
/// produce no alerts — the immune system stays at baseline.
///
/// **Biological mapping**: Cutaneous immune surveillance — the skin
/// continuously monitors for pathogens (external threats) and tissue
/// damage (internal threats) via distributed sensor networks.
pub fn skin_condition_to_alerts(condition: &SkinCondition) -> Vec<SkinAlert> {
    let mut alerts = Vec::new();

    // Temperature alerts (system load)
    match condition.temperature.status {
        SensorStatus::High => {
            alerts.push(SkinAlert {
                threat_level: ThreatLevel::High,
                threat_type: ThreatType::Damp, // Internal stress
                description: format!(
                    "thermal-stress:load={:.1}",
                    condition.temperature.value
                ),
            });
        }
        SensorStatus::Low => {
            alerts.push(SkinAlert {
                threat_level: ThreatLevel::Low,
                threat_type: ThreatType::Damp,
                description: format!(
                    "hypothermic:load={:.1}",
                    condition.temperature.value
                ),
            });
        }
        _ => {}
    }

    // Pressure alerts (queue depth / triggers)
    if condition.pressure.status == SensorStatus::High {
        alerts.push(SkinAlert {
            threat_level: ThreatLevel::Medium,
            threat_type: ThreatType::Pamp, // External pressure
            description: format!(
                "pressure-overload:triggers={:.1}",
                condition.pressure.value
            ),
        });
    }

    // Pain alerts (errors)
    if condition.pain.status == SensorStatus::Alert {
        alerts.push(SkinAlert {
            threat_level: ThreatLevel::Critical,
            threat_type: ThreatType::Damp, // Internal damage
            description: format!(
                "pain-signal:errors={:.1}",
                condition.pain.value
            ),
        });
    }

    alerts
}

/// Assess immune readiness from the integumentary shield state.
///
/// Returns a readiness score (0.0–1.0) based on how many protective
/// barriers are active.
///
/// **Biological mapping**: Skin barrier integrity — intact skin with
/// active antimicrobial peptides, commensal flora, and intact pH
/// provides strong passive immunity. Compromised barriers weaken defense.
pub fn shield_to_immune_readiness(shield: &Shield) -> f64 {
    let mut score = 0.0;
    if shield.auth_active {
        score += 0.34;
    }
    if shield.validation_active {
        score += 0.33;
    }
    if shield.monitoring_active {
        score += 0.33;
    }
    score
}

/// Compute the throughput metric for integumentary-immune coupling.
///
/// Returns the number of active alerts, representing the immune load
/// generated by skin-detected threats.
///
/// **Biological mapping**: Cutaneous immune activation level — more
/// skin alerts mean more Langerhans cell activation and more immune
/// trafficking to the site of injury.
pub fn skin_alert_throughput(condition: &SkinCondition) -> usize {
    skin_condition_to_alerts(condition).len()
}

/// Determine the overall threat level from a skin condition.
///
/// Returns the highest severity among all alerts, or Low if no alerts.
///
/// **Biological mapping**: Triage escalation — the immune system
/// responds to the most severe skin signal, not the average.
pub fn skin_max_threat(condition: &SkinCondition) -> ThreatLevel {
    let alerts = skin_condition_to_alerts(condition);
    alerts
        .iter()
        .map(|a| a.threat_level)
        .max()
        .unwrap_or(ThreatLevel::Low)
}

#[cfg(test)]
mod tests {
    use super::*;
    use nexcore_integumentary::{DermisSensors, SensorReading, SensorKind};

    fn make_normal_condition() -> SkinCondition {
        let sensors = DermisSensors;
        sensors.full_check(50.0, 10.0, 0.0)
    }

    fn make_alert_condition() -> SkinCondition {
        let sensors = DermisSensors;
        sensors.full_check(90.0, 20.0, 5.0)
    }

    #[test]
    fn test_normal_skin_no_alerts() {
        let condition = make_normal_condition();
        let alerts = skin_condition_to_alerts(&condition);
        assert!(alerts.is_empty(), "Normal skin should produce no alerts");
    }

    #[test]
    fn test_high_temp_produces_alert() {
        let condition = SkinCondition {
            temperature: SensorReading {
                kind: SensorKind::Temperature,
                value: 95.0,
                status: SensorStatus::High,
            },
            pressure: SensorReading {
                kind: SensorKind::Pressure,
                value: 10.0,
                status: SensorStatus::Normal,
            },
            pain: SensorReading {
                kind: SensorKind::Pain,
                value: 0.0,
                status: SensorStatus::Normal,
            },
            has_alert: true,
        };
        let alerts = skin_condition_to_alerts(&condition);
        assert_eq!(alerts.len(), 1);
        assert_eq!(alerts[0].threat_level, ThreatLevel::High);
        assert_eq!(alerts[0].threat_type, ThreatType::Damp);
        assert!(alerts[0].description.contains("thermal-stress"));
    }

    #[test]
    fn test_pain_produces_critical_alert() {
        let condition = SkinCondition {
            temperature: SensorReading {
                kind: SensorKind::Temperature,
                value: 50.0,
                status: SensorStatus::Normal,
            },
            pressure: SensorReading {
                kind: SensorKind::Pressure,
                value: 10.0,
                status: SensorStatus::Normal,
            },
            pain: SensorReading {
                kind: SensorKind::Pain,
                value: 3.0,
                status: SensorStatus::Alert,
            },
            has_alert: true,
        };
        let alerts = skin_condition_to_alerts(&condition);
        assert_eq!(alerts.len(), 1);
        assert_eq!(alerts[0].threat_level, ThreatLevel::Critical);
        assert!(alerts[0].description.contains("pain-signal"));
    }

    #[test]
    fn test_multiple_alerts() {
        let condition = make_alert_condition();
        let alerts = skin_condition_to_alerts(&condition);
        // High temp + High pressure + Pain alert = 3 alerts
        assert!(alerts.len() >= 2, "Multiple issues should produce multiple alerts: got {}", alerts.len());
    }

    #[test]
    fn test_shield_full_readiness() {
        let shield = Shield {
            auth_active: true,
            validation_active: true,
            monitoring_active: true,
        };
        let readiness = shield_to_immune_readiness(&shield);
        assert!(readiness > 0.99, "Full shield should give ~1.0 readiness: got {readiness}");
    }

    #[test]
    fn test_shield_partial_readiness() {
        let shield = Shield {
            auth_active: true,
            validation_active: false,
            monitoring_active: true,
        };
        let readiness = shield_to_immune_readiness(&shield);
        assert!((readiness - 0.67).abs() < 0.01);
    }

    #[test]
    fn test_shield_no_readiness() {
        let shield = Shield {
            auth_active: false,
            validation_active: false,
            monitoring_active: false,
        };
        let readiness = shield_to_immune_readiness(&shield);
        assert!((readiness - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_skin_alert_throughput_normal() {
        let condition = make_normal_condition();
        assert_eq!(skin_alert_throughput(&condition), 0);
    }

    #[test]
    fn test_skin_max_threat_normal() {
        let condition = make_normal_condition();
        assert_eq!(skin_max_threat(&condition), ThreatLevel::Low);
    }

    #[test]
    fn test_skin_max_threat_critical() {
        let condition = make_alert_condition();
        let max = skin_max_threat(&condition);
        // Should be at least High (pain produces Critical)
        assert!(max >= ThreatLevel::High, "Expected at least High: got {max}");
    }
}
